### YamlMime:PythonClass
uid: azure.core.exceptions.TooManyRedirectsError
name: TooManyRedirectsError
fullName: azure.core.exceptions.TooManyRedirectsError
module: azure.core.exceptions
inheritances:
- azure.core.exceptions.HttpResponseError
summary: Reached the maximum number of redirect attempts.
constructor:
  syntax: TooManyRedirectsError(history, *args, **kwargs)
  parameters:
  - name: history
methods:
- uid: azure.core.exceptions.TooManyRedirectsError.add_note
  name: add_note
  summary: "Exception.add_note(note) \u2013\nadd a note to the exception"
  signature: add_note()
- uid: azure.core.exceptions.TooManyRedirectsError.raise_with_traceback
  name: raise_with_traceback
  signature: raise_with_traceback()
- uid: azure.core.exceptions.TooManyRedirectsError.with_traceback
  name: with_traceback
  summary: "Exception.with_traceback(tb) \u2013\nset self.__traceback__ to tb and\
    \ return self."
  signature: with_traceback()
attributes:
- uid: azure.core.exceptions.TooManyRedirectsError.args
  name: args
- uid: azure.core.exceptions.TooManyRedirectsError.error
  name: error
  signature: 'error: ODataV4Format | None'
- uid: azure.core.exceptions.TooManyRedirectsError.model
  name: model
  signature: 'model: Any | None'
